server:
  port: 8081
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:serviciocivil
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true